//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWinformCallingWebAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientWinformCallingWebAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurs while deleting. Please refer the event viewer for details..
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required and should be a valid address.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while occures while getting the contact informations..
        /// </summary>
        internal static string ErrorDataGrid {
            get {
                return ResourceManager.GetString("ErrorDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurs while inserting / updating. Please refer the event viewer for details..
        /// </summary>
        internal static string ErrorInsertedUpdated {
            get {
                return ResourceManager.GetString("ErrorInsertedUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required and should be less than 51 characters.
        /// </summary>
        internal static string FirstNameValidator {
            get {
                return ResourceManager.GetString("FirstNameValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required and should be less than 51 characters.
        /// </summary>
        internal static string LasttNameValidator {
            get {
                return ResourceManager.GetString("LasttNameValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone no. is required and shoud be valid no.
        /// </summary>
        internal static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the row to delete..
        /// </summary>
        internal static string SelectRowDelete {
            get {
                return ResourceManager.GetString("SelectRowDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the row to update..
        /// </summary>
        internal static string SelectRowUpdate {
            get {
                return ResourceManager.GetString("SelectRowUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully inserted / updated..
        /// </summary>
        internal static string SucesfullyInsertUpdated {
            get {
                return ResourceManager.GetString("SucesfullyInsertUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully deleted..
        /// </summary>
        internal static string SucessfullyDeleted {
            get {
                return ResourceManager.GetString("SucessfullyDeleted", resourceCulture);
            }
        }
    }
}
